version : '3.6'
services:
  back:
    build : springio/souvenirs
    ports :
      - "8080:8080"
   environment:
     - "SPRING_PROFILES_ACTIVE=dev"

  front:
    build : bayesimpact/react-base:latest
    ports :
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080